export const AFRICAN_COUNTRIES = [
  { code: 'DZ', name: 'Algeria', nameEn: 'Algeria', currency: 'DZD', region: 'North Africa', flag: '🇩🇿' },
  { code: 'AO', name: 'Angola', nameEn: 'Angola', currency: 'AOA', region: 'Central Africa', flag: '🇦🇴' },
  { code: 'BJ', name: 'Bénin', nameEn: 'Benin', currency: 'XOF', region: 'West Africa', flag: '🇧🇯' },
  { code: 'BW', name: 'Botswana', nameEn: 'Botswana', currency: 'BWP', region: 'Southern Africa', flag: '🇧🇼' },
  { code: 'BF', name: 'Burkina Faso', nameEn: 'Burkina Faso', currency: 'XOF', region: 'West Africa', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', nameEn: 'Burundi', currency: 'BIF', region: 'East Africa', flag: '🇧🇮' },
  { code: 'CV', name: 'Cap-Vert', nameEn: 'Cape Verde', currency: 'CVE', region: 'West Africa', flag: '🇨🇻' },
  { code: 'CM', name: 'Cameroun', nameEn: 'Cameroon', currency: 'XAF', region: 'Central Africa', flag: '🇨🇲' },
  { code: 'CF', name: 'Centrafrique', nameEn: 'Central African Republic', currency: 'XAF', region: 'Central Africa', flag: '🇨🇫' },
  { code: 'TD', name: 'Tchad', nameEn: 'Chad', currency: 'XAF', region: 'Central Africa', flag: '🇹🇩' },
  { code: 'KM', name: 'Comores', nameEn: 'Comoros', currency: 'KMF', region: 'East Africa', flag: '🇰🇲' },
  { code: 'CG', name: 'Congo', nameEn: 'Congo', currency: 'XAF', region: 'Central Africa', flag: '🇨🇬' },
  { code: 'CD', name: 'RD Congo', nameEn: 'DR Congo', currency: 'CDF', region: 'Central Africa', flag: '🇨🇩' },
  { code: 'CI', name: "Côte d'Ivoire", nameEn: "Côte d'Ivoire", currency: 'XOF', region: 'West Africa', flag: '🇨🇮' },
  { code: 'DJ', name: 'Djibouti', nameEn: 'Djibouti', currency: 'DJF', region: 'East Africa', flag: '🇩🇯' },
  { code: 'EG', name: 'Égypte', nameEn: 'Egypt', currency: 'EGP', region: 'North Africa', flag: '🇪🇬' },
  { code: 'GQ', name: 'Guinée Équatoriale', nameEn: 'Equatorial Guinea', currency: 'XAF', region: 'Central Africa', flag: '🇬🇶' },
  { code: 'ER', name: 'Érythrée', nameEn: 'Eritrea', currency: 'ERN', region: 'East Africa', flag: '🇪🇷' },
  { code: 'SZ', name: 'Eswatini', nameEn: 'Eswatini', currency: 'SZL', region: 'Southern Africa', flag: '🇸🇿' },
  { code: 'ET', name: 'Éthiopie', nameEn: 'Ethiopia', currency: 'ETB', region: 'East Africa', flag: '🇪🇹' },
  { code: 'GA', name: 'Gabon', nameEn: 'Gabon', currency: 'XAF', region: 'Central Africa', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambie', nameEn: 'Gambia', currency: 'GMD', region: 'West Africa', flag: '🇬🇲' },
  { code: 'GH', name: 'Ghana', nameEn: 'Ghana', currency: 'GHS', region: 'West Africa', flag: '🇬🇭' },
  { code: 'GN', name: 'Guinée', nameEn: 'Guinea', currency: 'GNF', region: 'West Africa', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinée-Bissau', nameEn: 'Guinea-Bissau', currency: 'XOF', region: 'West Africa', flag: '🇬🇼' },
  { code: 'KE', name: 'Kenya', nameEn: 'Kenya', currency: 'KES', region: 'East Africa', flag: '🇰🇪' },
  { code: 'LS', name: 'Lesotho', nameEn: 'Lesotho', currency: 'LSL', region: 'Southern Africa', flag: '🇱🇸' },
  { code: 'LR', name: 'Liberia', nameEn: 'Liberia', currency: 'LRD', region: 'West Africa', flag: '🇱🇷' },
  { code: 'LY', name: 'Libye', nameEn: 'Libya', currency: 'LYD', region: 'North Africa', flag: '🇱🇾' },
  { code: 'MG', name: 'Madagascar', nameEn: 'Madagascar', currency: 'MGA', region: 'East Africa', flag: '🇲🇬' },
  { code: 'MW', name: 'Malawi', nameEn: 'Malawi', currency: 'MWK', region: 'East Africa', flag: '🇲🇼' },
  { code: 'ML', name: 'Mali', nameEn: 'Mali', currency: 'XOF', region: 'West Africa', flag: '🇲🇱' },
  { code: 'MR', name: 'Mauritanie', nameEn: 'Mauritania', currency: 'MRU', region: 'North Africa', flag: '🇲🇷' },
  { code: 'MU', name: 'Maurice', nameEn: 'Mauritius', currency: 'MUR', region: 'East Africa', flag: '🇲🇺' },
  { code: 'MA', name: 'Maroc', nameEn: 'Morocco', currency: 'MAD', region: 'North Africa', flag: '🇲🇦' },
  { code: 'MZ', name: 'Mozambique', nameEn: 'Mozambique', currency: 'MZN', region: 'East Africa', flag: '🇲🇿' },
  { code: 'NA', name: 'Namibie', nameEn: 'Namibia', currency: 'NAD', region: 'Southern Africa', flag: '🇳🇦' },
  { code: 'NE', name: 'Niger', nameEn: 'Niger', currency: 'XOF', region: 'West Africa', flag: '🇳🇪' },
  { code: 'NG', name: 'Nigeria', nameEn: 'Nigeria', currency: 'NGN', region: 'West Africa', flag: '🇳🇬' },
  { code: 'RW', name: 'Rwanda', nameEn: 'Rwanda', currency: 'RWF', region: 'East Africa', flag: '🇷🇼' },
  { code: 'ST', name: 'São Tomé-et-Príncipe', nameEn: 'São Tomé and Príncipe', currency: 'STN', region: 'Central Africa', flag: '🇸🇹' },
  { code: 'SN', name: 'Sénégal', nameEn: 'Senegal', currency: 'XOF', region: 'West Africa', flag: '🇸🇳' },
  { code: 'SC', name: 'Seychelles', nameEn: 'Seychelles', currency: 'SCR', region: 'East Africa', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', nameEn: 'Sierra Leone', currency: 'SLL', region: 'West Africa', flag: '🇸🇱' },
  { code: 'SO', name: 'Somalie', nameEn: 'Somalia', currency: 'SOS', region: 'East Africa', flag: '🇸🇴' },
  { code: 'ZA', name: 'Afrique du Sud', nameEn: 'South Africa', currency: 'ZAR', region: 'Southern Africa', flag: '🇿🇦' },
  { code: 'SS', name: 'Soudan du Sud', nameEn: 'South Sudan', currency: 'SSP', region: 'East Africa', flag: '🇸🇸' },
  { code: 'SD', name: 'Soudan', nameEn: 'Sudan', currency: 'SDG', region: 'North Africa', flag: '🇸🇩' },
  { code: 'TZ', name: 'Tanzanie', nameEn: 'Tanzania', currency: 'TZS', region: 'East Africa', flag: '🇹🇿' },
  { code: 'TG', name: 'Togo', nameEn: 'Togo', currency: 'XOF', region: 'West Africa', flag: '🇹🇬' },
  { code: 'TN', name: 'Tunisie', nameEn: 'Tunisia', currency: 'TND', region: 'North Africa', flag: '🇹🇳' },
  { code: 'UG', name: 'Ouganda', nameEn: 'Uganda', currency: 'UGX', region: 'East Africa', flag: '🇺🇬' },
  { code: 'ZM', name: 'Zambie', nameEn: 'Zambia', currency: 'ZMW', region: 'Southern Africa', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', nameEn: 'Zimbabwe', currency: 'ZWL', region: 'Southern Africa', flag: '🇿🇼' },
];

export const PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    price: 9,
    annualPrice: 79,
    color: 'text-gray-700',
    bg: 'bg-gray-50',
    border: 'border-gray-200',
    products: 15,
    staff: 1,
    aiGenerations: 20,
    customDomain: false,
    videoAI: false,
    chatbotAI: false,
    accountingAI: false,
    marketplaceListing: false,
    verifiedBadge: false,
    apiAccess: false,
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 19,
    annualPrice: 159,
    color: 'text-orange-600',
    bg: 'bg-orange-50',
    border: 'border-orange-300',
    popular: true,
    products: 1000,
    staff: 5,
    aiGenerations: 200,
    customDomain: true,
    videoAI: true,
    chatbotAI: true,
    accountingAI: true,
    marketplaceListing: true,
    verifiedBadge: true,
    apiAccess: false,
  },
  {
    id: 'enterprise',
    name: 'Entreprise',
    price: 69,
    annualPrice: 599,
    color: 'text-gray-900',
    bg: 'bg-gray-900',
    border: 'border-gray-800',
    dark: true,
    products: -1,
    staff: -1,
    aiGenerations: -1,
    customDomain: true,
    videoAI: true,
    chatbotAI: true,
    accountingAI: true,
    marketplaceListing: true,
    verifiedBadge: true,
    apiAccess: true,
  },
];

export const SUPER_ADMIN_EMAILS = [
  'webdxb1@gmail.com',
  'vincentnogue@yahoo.com',
  'vincentnogue2@gmail.com',
];
