// African countries with major cities for dropdowns
export const COUNTRIES_CITIES: Record<string, string[]> = {
  'Côte d\'Ivoire': ['Abidjan', 'Bouaké', 'Daloa', 'Yamoussoukro', 'San-Pédro', 'Korhogo', 'Man', 'Divo', 'Gagnoa', 'Séguéla'],
  'Sénégal': ['Dakar', 'Thiès', 'Touba', 'Saint-Louis', 'Kaolack', 'Ziguinchor', 'Diourbel', 'Louga', 'Tambacounda', 'Mbour'],
  'Nigeria': ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt', 'Benin City', 'Kaduna', 'Maiduguri', 'Enugu', 'Aba'],
  'Ghana': ['Accra', 'Kumasi', 'Tamale', 'Takoradi', 'Cape Coast', 'Tema', 'Obuasi', 'Sunyani', 'Ho', 'Wa'],
  'Cameroun': ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam', 'Garoua', 'Maroua', 'Ngaoundéré', 'Kribi', 'Limbé', 'Buea'],
  'Mali': ['Bamako', 'Sikasso', 'Ségou', 'Mopti', 'Kayes', 'Tombouctou', 'Gao', 'Kidal', 'San', 'Djenné'],
  'Burkina Faso': ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora', 'Ouahigouya', 'Kaya', 'Tenkodogo', 'Fada N\'gourma', 'Dédougou', 'Dori'],
  'Niger': ['Niamey', 'Zinder', 'Maradi', 'Agadez', 'Tahoua', 'Diffa', 'Dosso', 'Tillabéri', 'Mirriah', 'Tessaoua'],
  'Bénin': ['Cotonou', 'Porto-Novo', 'Parakou', 'Abomey', 'Kandi', 'Natitingou', 'Lokossa', 'Ouidah', 'Bohicon', 'Djougou'],
  'Togo': ['Lomé', 'Sokodé', 'Kara', 'Atakpamé', 'Dapaong', 'Tsévié', 'Aného', 'Mango', 'Badou', 'Sotouboua'],
  'Guinée': ['Conakry', 'Kankan', 'Kindia', 'Nzérékoré', 'Labé', 'Siguiri', 'Kissidougou', 'Macenta', 'Dabola', 'Fria'],
  'Gabon': ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda', 'Mouila', 'Lambaréné', 'Tchibanga', 'Koulamoutou', 'Makokou'],
  'Congo': ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Impfondo', 'Owando', 'Madingou', 'Sibiti', 'Mossendjo', 'Kinkala'],
  'RD Congo': ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani', 'Goma', 'Bukavu', 'Matadi', 'Mbandaka', 'Likasi'],
  'Tchad': ['N\'Djamena', 'Moundou', 'Sarh', 'Abéché', 'Kelo', 'Mongo', 'Doba', 'Bongor', 'Faya-Largeau', 'Am Timan'],
  'Centrafrique': ['Bangui', 'Bimbo', 'Mbaïki', 'Berbérati', 'Kaga Bandoro', 'Carnot', 'Bouar', 'Bossangoa', 'Bambari', 'Batangafo'],
  'Maroc': ['Casablanca', 'Rabat', 'Marrakech', 'Fès', 'Tanger', 'Agadir', 'Meknès', 'Oujda', 'Kénitra', 'Tétouan'],
  'Algérie': ['Alger', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Sétif', 'Batna', 'Tlemcen', 'Béjaïa', 'Tizi Ouzou'],
  'Tunisie': ['Tunis', 'Sfax', 'Sousse', 'Kairouan', 'Bizerte', 'Gabès', 'Ariana', 'Gafsa', 'Monastir', 'La Marsa'],
  'Kenya': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Malindi', 'Kitale', 'Garissa', 'Kakamega', 'Machakos'],
  'Tanzanie': ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Mbeya', 'Morogoro', 'Tanga', 'Kigoma', 'Sumbawanga', 'Kahama'],
  'Ouganda': ['Kampala', 'Wakiso', 'Mukono', 'Jinja', 'Mbarara', 'Gulu', 'Lira', 'Mbale', 'Masaka', 'Entebbe'],
  'Rwanda': ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri', 'Gisenyi', 'Byumba', 'Cyangugu', 'Kibungo', 'Rwamagana', 'Kibuye'],
  'Éthiopie': ['Addis-Abeba', 'Dire Dawa', 'Adama', 'Gondar', 'Dessie', 'Jimma', 'Bahir Dar', 'Mekele', 'Hawassa', 'Shashamane'],
  'Afrique du Sud': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Pietermaritzburg', 'Polokwane', 'Nelspruit'],
  'Zimbabwe': ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru', 'Kwekwe', 'Kadoma', 'Masvingo', 'Chegutu', 'Norton'],
  'Zambie': ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Chingola', 'Mufulira', 'Livingstone', 'Luanshya', 'Kasama', 'Chipata'],
  'Madagascar': ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga', 'Toliara', 'Antsiranana', 'Nosy Be', 'Morondava', 'Manakara'],
  'Maurice': ['Port-Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix', 'Curepipe', 'Quatre Bornes', 'Goodlands', 'Port Mathurin', 'Mahébourg', 'Souillac', 'Pamplemousses'],
  'Cap-Vert': ['Praia', 'Mindelo', 'Santa Maria', 'Espargos', 'Assomada', 'Porto Novo', 'Ribeira Grande', 'São Filipe', 'Tarrafal', 'Vila da Ribeira Brava'],
  'Liberia': ['Monrovia', 'Gbarnga', 'Kakata', 'Bensonville', 'Harper', 'Buchanan', 'Greenville', 'Robertsport', 'Voinjama', 'Zwedru'],
  'Sierra Leone': ['Freetown', 'Bo', 'Kenema', 'Makeni', 'Koidu', 'Lunsar', 'Waterloo', 'Magburaka', 'Kabala', 'Port Loko'],
  'Gambie': ['Banjul', 'Serekunda', 'Brikama', 'Bakau', 'Farafenni', 'Basse Santa Su', 'Bansang', 'Janjanbureh', 'Kuntaur', 'Kerewan'],
  'Mauritanie': ['Nouakchott', 'Nouadhibou', 'Rosso', 'Kaédi', 'Zouérat', 'Atar', 'Néma', 'Sélibaby', 'Aleg', 'Tidjikja'],
  'Soudan': ['Khartoum', 'Omdurman', 'Port Sudan', 'Kassala', 'Al-Qadarif', 'Wad Madani', 'Dongola', 'Nyala', 'El Fasher', 'El Obeid'],
  'Égypte': ['Le Caire', 'Alexandrie', 'Gizeh', 'Louxor', 'Assouan', 'Port-Saïd', 'Suez', 'Ismailia', 'Mansourah', 'Tanta'],
};

export const COUNTRIES = Object.keys(COUNTRIES_CITIES).sort();

// Code pays (ISO) + devise par défaut, utilisés pour remplir automatiquement
// country_code et currency dans l'onboarding
export const COUNTRY_INFO: Record<string, { code: string; currency: string }> = {
  'Côte d\'Ivoire': { code: 'CI', currency: 'XOF' },
  'Sénégal': { code: 'SN', currency: 'XOF' },
  'Nigeria': { code: 'NG', currency: 'NGN' },
  'Ghana': { code: 'GH', currency: 'GHS' },
  'Cameroun': { code: 'CM', currency: 'XAF' },
  'Mali': { code: 'ML', currency: 'XOF' },
  'Burkina Faso': { code: 'BF', currency: 'XOF' },
  'Niger': { code: 'NE', currency: 'XOF' },
  'Bénin': { code: 'BJ', currency: 'XOF' },
  'Togo': { code: 'TG', currency: 'XOF' },
  'Guinée': { code: 'GN', currency: 'GNF' },
  'Gabon': { code: 'GA', currency: 'XAF' },
  'Congo': { code: 'CG', currency: 'XAF' },
  'RD Congo': { code: 'CD', currency: 'CDF' },
  'Tchad': { code: 'TD', currency: 'XAF' },
  'Centrafrique': { code: 'CF', currency: 'XAF' },
  'Maroc': { code: 'MA', currency: 'MAD' },
  'Algérie': { code: 'DZ', currency: 'DZD' },
  'Tunisie': { code: 'TN', currency: 'TND' },
  'Kenya': { code: 'KE', currency: 'KES' },
  'Tanzanie': { code: 'TZ', currency: 'TZS' },
  'Ouganda': { code: 'UG', currency: 'UGX' },
  'Rwanda': { code: 'RW', currency: 'RWF' },
  'Éthiopie': { code: 'ET', currency: 'ETB' },
  'Afrique du Sud': { code: 'ZA', currency: 'ZAR' },
  'Zimbabwe': { code: 'ZW', currency: 'ZWL' },
  'Zambie': { code: 'ZM', currency: 'ZMW' },
  'Madagascar': { code: 'MG', currency: 'MGA' },
  'Maurice': { code: 'MU', currency: 'MUR' },
  'Cap-Vert': { code: 'CV', currency: 'CVE' },
  'Liberia': { code: 'LR', currency: 'LRD' },
  'Sierra Leone': { code: 'SL', currency: 'SLL' },
  'Gambie': { code: 'GM', currency: 'GMD' },
  'Mauritanie': { code: 'MR', currency: 'MRU' },
  'Soudan': { code: 'SD', currency: 'SDG' },
  'Égypte': { code: 'EG', currency: 'EGP' },
};

export const CURRENCIES = [
  { code: 'XOF', label: 'Franc CFA UEMOA (XOF)', symbol: 'F' },
  { code: 'XAF', label: 'Franc CFA CEMAC (XAF)', symbol: 'FCFA' },
  { code: 'NGN', label: 'Naira (NGN)', symbol: '₦' },
  { code: 'GHS', label: 'Cedi (GHS)', symbol: '₵' },
  { code: 'GNF', label: 'Franc Guinéen (GNF)', symbol: 'FG' },
  { code: 'CDF', label: 'Franc Congolais (CDF)', symbol: 'FC' },
  { code: 'USD', label: 'Dollar US (USD)', symbol: '$' },
  { code: 'EUR', label: 'Euro (EUR)', symbol: '€' },
  { code: 'GBP', label: 'Livre Sterling (GBP)', symbol: '£' },
  { code: 'MAD', label: 'Dirham (MAD)', symbol: 'DH' },
  { code: 'DZD', label: 'Dinar Algérien (DZD)', symbol: 'DA' },
  { code: 'TND', label: 'Dinar Tunisien (TND)', symbol: 'DT' },
  { code: 'EGP', label: 'Livre Égyptienne (EGP)', symbol: 'E£' },
  { code: 'KES', label: 'Shilling Kényan (KES)', symbol: 'KSh' },
  { code: 'TZS', label: 'Shilling Tanzanien (TZS)', symbol: 'TSh' },
  { code: 'UGX', label: 'Shilling Ougandais (UGX)', symbol: 'USh' },
  { code: 'RWF', label: 'Franc Rwandais (RWF)', symbol: 'FRw' },
  { code: 'ETB', label: 'Birr Éthiopien (ETB)', symbol: 'Br' },
  { code: 'ZAR', label: 'Rand (ZAR)', symbol: 'R' },
  { code: 'ZWL', label: 'Dollar Zimbabwéen (ZWL)', symbol: 'Z$' },
  { code: 'ZMW', label: 'Kwacha Zambien (ZMW)', symbol: 'ZK' },
  { code: 'MGA', label: 'Ariary Malgache (MGA)', symbol: 'Ar' },
  { code: 'MUR', label: 'Roupie Mauricienne (MUR)', symbol: '₨' },
  { code: 'CVE', label: 'Escudo Cap-Verdien (CVE)', symbol: '$' },
  { code: 'LRD', label: 'Dollar Libérien (LRD)', symbol: 'L$' },
  { code: 'SLL', label: 'Leone (SLL)', symbol: 'Le' },
  { code: 'GMD', label: 'Dalasi (GMD)', symbol: 'D' },
  { code: 'MRU', label: 'Ouguiya (MRU)', symbol: 'UM' },
  { code: 'SDG', label: 'Livre Soudanaise (SDG)', symbol: 'SDG' },
];

export const LANGUAGES = [
  { code: 'fr', label: 'Français' },
  { code: 'en', label: 'English' },
  { code: 'wo', label: 'Wolof' },
  { code: 'bm', label: 'Bambara' },
  { code: 'sw', label: 'Swahili' },
  { code: 'ar', label: 'العربية' },
  { code: 'pt', label: 'Português' },
  { code: 'am', label: 'አማርኛ' },
  { code: 'yo', label: 'Yoruba' },
  { code: 'ha', label: 'Hausa' },
  { code: 'ig', label: 'Igbo' },
];
