export const AFRICAN_COUNTRIES = [
  { code: 'DZ', name: 'Algeria', nameEn: 'Algeria', currency: 'DZD', region: 'North Africa', flag: '🇩🇿' },
  { code: 'AO', name: 'Angola', nameEn: 'Angola', currency: 'AOA', region: 'Central Africa', flag: '🇦🇴' },
  { code: 'BJ', name: 'Bénin', nameEn: 'Benin', currency: 'XOF', region: 'West Africa', flag: '🇧🇯' },
  { code: 'BW', name: 'Botswana', nameEn: 'Botswana', currency: 'BWP', region: 'Southern Africa', flag: '🇧🇼' },
  { code: 'BF', name: 'Burkina Faso', nameEn: 'Burkina Faso', currency: 'XOF', region: 'West Africa', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', nameEn: 'Burundi', currency: 'BIF', region: 'East Africa', flag: '🇧🇮' },
  { code: 'CV', name: 'Cap-Vert', nameEn: 'Cape Verde', currency: 'CVE', region: 'West Africa', flag: '🇨🇻' },
  { code: 'CM', name: 'Cameroun', nameEn: 'Cameroon', currency: 'XAF', region: 'Central Africa', flag: '🇨🇲' },
  { code: 'CF', name: 'Centrafrique', nameEn: 'Central African Republic', currency: 'XAF', region: 'Central Africa', flag: '🇨🇫' },
  { code: 'TD', name: 'Tchad', nameEn: 'Chad', currency: 'XAF', region: 'Central Africa', flag: '🇹🇩' },
  { code: 'KM', name: 'Comores', nameEn: 'Comoros', currency: 'KMF', region: 'East Africa', flag: '🇰🇲' },
  { code: 'CG', name: 'Congo', nameEn: 'Congo', currency: 'XAF', region: 'Central Africa', flag: '🇨🇬' },
  { code: 'CD', name: 'RD Congo', nameEn: 'DR Congo', currency: 'CDF', region: 'Central Africa', flag: '🇨🇩' },
  { code: 'CI', name: "Côte d'Ivoire", nameEn: "Côte d'Ivoire", currency: 'XOF', region: 'West Africa', flag: '🇨🇮' },
  { code: 'DJ', name: 'Djibouti', nameEn: 'Djibouti', currency: 'DJF', region: 'East Africa', flag: '🇩🇯' },
  { code: 'EG', name: 'Égypte', nameEn: 'Egypt', currency: 'EGP', region: 'North Africa', flag: '🇪🇬' },
  { code: 'GQ', name: 'Guinée Équatoriale', nameEn: 'Equatorial Guinea', currency: 'XAF', region: 'Central Africa', flag: '🇬🇶' },
  { code: 'ER', name: 'Érythrée', nameEn: 'Eritrea', currency: 'ERN', region: 'East Africa', flag: '🇪🇷' },
  { code: 'SZ', name: 'Eswatini', nameEn: 'Eswatini', currency: 'SZL', region: 'Southern Africa', flag: '🇸🇿' },
  { code: 'ET', name: 'Éthiopie', nameEn: 'Ethiopia', currency: 'ETB', region: 'East Africa', flag: '🇪🇹' },
  { code: 'GA', name: 'Gabon', nameEn: 'Gabon', currency: 'XAF', region: 'Central Africa', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambie', nameEn: 'Gambia', currency: 'GMD', region: 'West Africa', flag: '🇬🇲' },
  { code: 'GH', name: 'Ghana', nameEn: 'Ghana', currency: 'GHS', region: 'West Africa', flag: '🇬🇭' },
  { code: 'GN', name: 'Guinée', nameEn: 'Guinea', currency: 'GNF', region: 'West Africa', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinée-Bissau', nameEn: 'Guinea-Bissau', currency: 'XOF', region: 'West Africa', flag: '🇬🇼' },
  { code: 'KE', name: 'Kenya', nameEn: 'Kenya', currency: 'KES', region: 'East Africa', flag: '🇰🇪' },
  { code: 'LS', name: 'Lesotho', nameEn: 'Lesotho', currency: 'LSL', region: 'Southern Africa', flag: '🇱🇸' },
  { code: 'LR', name: 'Liberia', nameEn: 'Liberia', currency: 'LRD', region: 'West Africa', flag: '🇱🇷' },
  { code: 'LY', name: 'Libye', nameEn: 'Libya', currency: 'LYD', region: 'North Africa', flag: '🇱🇾' },
  { code: 'MG', name: 'Madagascar', nameEn: 'Madagascar', currency: 'MGA', region: 'East Africa', flag: '🇲🇬' },
  { code: 'MW', name: 'Malawi', nameEn: 'Malawi', currency: 'MWK', region: 'East Africa', flag: '🇲🇼' },
  { code: 'ML', name: 'Mali', nameEn: 'Mali', currency: 'XOF', region: 'West Africa', flag: '🇲🇱' },
  { code: 'MR', name: 'Mauritanie', nameEn: 'Mauritania', currency: 'MRU', region: 'North Africa', flag: '🇲🇷' },
  { code: 'MU', name: 'Maurice', nameEn: 'Mauritius', currency: 'MUR', region: 'East Africa', flag: '🇲🇺' },
  { code: 'MA', name: 'Maroc', nameEn: 'Morocco', currency: 'MAD', region: 'North Africa', flag: '🇲🇦' },
  { code: 'MZ', name: 'Mozambique', nameEn: 'Mozambique', currency: 'MZN', region: 'East Africa', flag: '🇲🇿' },
  { code: 'NA', name: 'Namibie', nameEn: 'Namibia', currency: 'NAD', region: 'Southern Africa', flag: '🇳🇦' },
  { code: 'NE', name: 'Niger', nameEn: 'Niger', currency: 'XOF', region: 'West Africa', flag: '🇳🇪' },
  { code: 'NG', name: 'Nigeria', nameEn: 'Nigeria', currency: 'NGN', region: 'West Africa', flag: '🇳🇬' },
  { code: 'RW', name: 'Rwanda', nameEn: 'Rwanda', currency: 'RWF', region: 'East Africa', flag: '🇷🇼' },
  { code: 'ST', name: 'São Tomé-et-Príncipe', nameEn: 'São Tomé and Príncipe', currency: 'STN', region: 'Central Africa', flag: '🇸🇹' },
  { code: 'SN', name: 'Sénégal', nameEn: 'Senegal', currency: 'XOF', region: 'West Africa', flag: '🇸🇳' },
  { code: 'SC', name: 'Seychelles', nameEn: 'Seychelles', currency: 'SCR', region: 'East Africa', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', nameEn: 'Sierra Leone', currency: 'SLL', region: 'West Africa', flag: '🇸🇱' },
  { code: 'SO', name: 'Somalie', nameEn: 'Somalia', currency: 'SOS', region: 'East Africa', flag: '🇸🇴' },
  { code: 'ZA', name: 'Afrique du Sud', nameEn: 'South Africa', currency: 'ZAR', region: 'Southern Africa', flag: '🇿🇦' },
  { code: 'SS', name: 'Soudan du Sud', nameEn: 'South Sudan', currency: 'SSP', region: 'East Africa', flag: '🇸🇸' },
  { code: 'SD', name: 'Soudan', nameEn: 'Sudan', currency: 'SDG', region: 'North Africa', flag: '🇸🇩' },
  { code: 'TZ', name: 'Tanzanie', nameEn: 'Tanzania', currency: 'TZS', region: 'East Africa', flag: '🇹🇿' },
  { code: 'TG', name: 'Togo', nameEn: 'Togo', currency: 'XOF', region: 'West Africa', flag: '🇹🇬' },
  { code: 'TN', name: 'Tunisie', nameEn: 'Tunisia', currency: 'TND', region: 'North Africa', flag: '🇹🇳' },
  { code: 'UG', name: 'Ouganda', nameEn: 'Uganda', currency: 'UGX', region: 'East Africa', flag: '🇺🇬' },
  { code: 'ZM', name: 'Zambie', nameEn: 'Zambia', currency: 'ZMW', region: 'Southern Africa', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', nameEn: 'Zimbabwe', currency: 'ZWL', region: 'Southern Africa', flag: '🇿🇼' },
];

export const PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    price: 9,
    annualPrice: 79,
    color: 'text-gray-700',
    bg: 'bg-gray-50',
    border: 'border-gray-200',
    products: 15,
    staff: 1,
    aiGenerations: 20,
    videoAI: false,
    chatbotAI: false,
    accountingAI: false,
    marketplaceListing: false,
    verifiedBadge: false,
    apiAccess: false,
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 19,
    annualPrice: 159,
    color: 'text-brand-600',
    bg: 'bg-brand-50',
    border: 'border-brand-300',
    popular: true,
    products: 1000,
    staff: 5,
    aiGenerations: 200,
    videoAI: true,
    chatbotAI: true,
    accountingAI: true,
    marketplaceListing: true,
    verifiedBadge: true,
    apiAccess: false,
  },
  {
    id: 'enterprise',
    name: 'Entreprise',
    price: 69,
    annualPrice: 599,
    color: 'text-gray-900',
    bg: 'bg-gray-900',
    border: 'border-gray-800',
    dark: true,
    products: -1,
    staff: -1,
    aiGenerations: -1,
    videoAI: true,
    chatbotAI: true,
    accountingAI: true,
    marketplaceListing: true,
    verifiedBadge: true,
    apiAccess: true,
  },
];

export const SUPER_ADMIN_EMAILS = [
  'webdxb1@gmail.com',
  'vincentnogue@yahoo.com',
  'vincentnogue2@gmail.com',
];

export interface GlobalCountry {
  code: string;
  name: string;
  nameEn: string;
  currency: string;
  flag: string;
}

export const GLOBAL_COUNTRIES: GlobalCountry[] = [
  { code: 'US', name: 'États-Unis', nameEn: 'United States', currency: 'USD', flag: '🇺🇸' },
  { code: 'FR', name: 'France', nameEn: 'France', currency: 'EUR', flag: '🇫🇷' },
  { code: 'CA', name: 'Canada', nameEn: 'Canada', currency: 'CAD', flag: '🇨🇦' },
  { code: 'GB', name: 'Royaume-Uni', nameEn: 'United Kingdom', currency: 'GBP', flag: '🇬🇧' },
  { code: 'DE', name: 'Allemagne', nameEn: 'Germany', currency: 'EUR', flag: '🇩🇪' },
  { code: 'IT', name: 'Italie', nameEn: 'Italy', currency: 'EUR', flag: '🇮🇹' },
  { code: 'ES', name: 'Espagne', nameEn: 'Spain', currency: 'EUR', flag: '🇪🇸' },
  { code: 'BE', name: 'Belgique', nameEn: 'Belgium', currency: 'EUR', flag: '🇧🇪' },
  { code: 'CH', name: 'Suisse', nameEn: 'Switzerland', currency: 'CHF', flag: '🇨🇭' },
  { code: 'JP', name: 'Japon', nameEn: 'Japan', currency: 'JPY', flag: '🇯🇵' },
  { code: 'CN', name: 'Chine', nameEn: 'China', currency: 'CNY', flag: '🇨🇳' },
  { code: 'AU', name: 'Australie', nameEn: 'Australia', currency: 'AUD', flag: '🇦🇺' },
  { code: 'BR', name: 'Brésil', nameEn: 'Brazil', currency: 'BRL', flag: '🇧🇷' },
  { code: 'IN', name: 'Inde', nameEn: 'India', currency: 'INR', flag: '🇮🇳' },
  { code: 'MX', name: 'Mexique', nameEn: 'Mexico', currency: 'MXN', flag: '🇲🇽' },
  { code: 'KR', name: 'Corée du Sud', nameEn: 'South Korea', currency: 'KRW', flag: '🇰🇷' },
  { code: 'AE', name: 'Émirats Arabes Unis', nameEn: 'United Arab Emirates', currency: 'AED', flag: '🇦🇪' },
  { code: 'SA', name: 'Arabie Saoudite', nameEn: 'Saudi Arabia', currency: 'SAR', flag: '🇸🇦' },
  { code: 'SG', name: 'Singapour', nameEn: 'Singapore', currency: 'SGD', flag: '🇸🇬' },
  { code: 'TR', name: 'Turquie', nameEn: 'Turkey', currency: 'TRY', flag: '🇹🇷' },
  { code: 'RU', name: 'Russie', nameEn: 'Russia', currency: 'RUB', flag: '🇷🇺' },
  { code: 'AR', name: 'Argentine', nameEn: 'Argentina', currency: 'ARS', flag: '🇦🇷' },
  { code: 'CO', name: 'Colombie', nameEn: 'Colombia', currency: 'COP', flag: '🇨🇴' },
  { code: 'CL', name: 'Chili', nameEn: 'Chile', currency: 'CLP', flag: '🇨🇱' },
  { code: 'PE', name: 'Pérou', nameEn: 'Peru', currency: 'PEN', flag: '🇵🇪' },
  { code: 'NZ', name: 'Nouvelle-Zélande', nameEn: 'New Zealand', currency: 'NZD', flag: '🇳🇿' },
  { code: 'NL', name: 'Pays-Bas', nameEn: 'Netherlands', currency: 'EUR', flag: '🇳🇱' },
  { code: 'SE', name: 'Suède', nameEn: 'Sweden', currency: 'SEK', flag: '🇸🇪' },
  { code: 'NO', name: 'Norvège', nameEn: 'Norway', currency: 'NOK', flag: '🇳🇴' },
  { code: 'DK', name: 'Danemark', nameEn: 'Denmark', currency: 'DKK', flag: '🇩🇰' },
  { code: 'FI', name: 'Finlande', nameEn: 'Finland', currency: 'EUR', flag: '🇫🇮' },
  { code: 'IE', name: 'Irlande', nameEn: 'Ireland', currency: 'EUR', flag: '🇮🇪' },
  { code: 'AT', name: 'Autriche', nameEn: 'Austria', currency: 'EUR', flag: '🇦🇹' },
  { code: 'PT', name: 'Portugal', nameEn: 'Portugal', currency: 'EUR', flag: '🇵🇹' },
  { code: 'GR', name: 'Grèce', nameEn: 'Greece', currency: 'EUR', flag: '🇬🇷' },
  { code: 'PL', name: 'Pologne', nameEn: 'Poland', currency: 'PLN', flag: '🇵🇱' },
  { code: 'IL', name: 'Israël', nameEn: 'Israel', currency: 'ILS', flag: '🇮🇱' },
  { code: 'MY', name: 'Malaisie', nameEn: 'Malaysia', currency: 'MYR', flag: '🇲🇾' },
  { code: 'TH', name: 'Thaïlande', nameEn: 'Thailand', currency: 'THB', flag: '🇹🇭' },
  { code: 'ID', name: 'Indonésie', nameEn: 'Indonesia', currency: 'IDR', flag: '🇮🇩' },
  { code: 'VN', name: 'Vietnam', nameEn: 'Vietnam', currency: 'VND', flag: '🇻🇳' },
  { code: 'PH', name: 'Philippines', nameEn: 'Philippines', currency: 'PHP', flag: '🇵🇭' },
  { code: 'PK', name: 'Pakistan', nameEn: 'Pakistan', currency: 'PKR', flag: '🇵🇰' },
  { code: 'BD', name: 'Bangladesh', nameEn: 'Bangladesh', currency: 'BDT', flag: '🇧🇩' },
  { code: 'UA', name: 'Ukraine', nameEn: 'Ukraine', currency: 'UAH', flag: '🇺🇦' },
  { code: 'RO', name: 'Roumanie', nameEn: 'Romania', currency: 'RON', flag: '🇷🇴' },
  { code: 'CZ', name: 'République Tchèque', nameEn: 'Czech Republic', currency: 'CZK', flag: '🇨🇿' },
  { code: 'HU', name: 'Hongrie', nameEn: 'Hungary', currency: 'HUF', flag: '🇭🇺' },
  { code: 'VE', name: 'Venezuela', nameEn: 'Venezuela', currency: 'VES', flag: '🇻🇪' },
  { code: 'EC', name: 'Équateur', nameEn: 'Ecuador', currency: 'USD', flag: '🇪🇨' },
  { code: 'BO', name: 'Bolivie', nameEn: 'Bolivia', currency: 'BOB', flag: '🇧🇴' },
  { code: 'PY', name: 'Paraguay', nameEn: 'Paraguay', currency: 'PYG', flag: '🇵🇾' },
  { code: 'UY', name: 'Uruguay', nameEn: 'Uruguay', currency: 'UYU', flag: '🇺🇾' },
  { code: 'CR', name: 'Costa Rica', nameEn: 'Costa Rica', currency: 'CRC', flag: '🇨🇷' },
  { code: 'PA', name: 'Panama', nameEn: 'Panama', currency: 'PAB', flag: '🇵🇦' },
  { code: 'CU', name: 'Cuba', nameEn: 'Cuba', currency: 'CUP', flag: '🇨🇺' },
  { code: 'JM', name: 'Jamaïque', nameEn: 'Jamaica', currency: 'JMD', flag: '🇯🇲' },
  { code: 'DO', name: 'République Dominicaine', nameEn: 'Dominican Republic', currency: 'DOP', flag: '🇩🇴' },
  { code: 'HT', name: 'Haïti', nameEn: 'Haiti', currency: 'HTG', flag: '🇭🇹' },
  { code: 'SV', name: 'El Salvador', nameEn: 'El Salvador', currency: 'USD', flag: '🇸🇻' },
  { code: 'GT', name: 'Guatemala', nameEn: 'Guatemala', currency: 'GTQ', flag: '🇬🇹' },
  { code: 'HN', name: 'Honduras', nameEn: 'Honduras', currency: 'HNL', flag: '🇭🇳' },
  { code: 'NI', name: 'Nicaragua', nameEn: 'Nicaragua', currency: 'NIO', flag: '🇳🇮' },
  { code: 'BS', name: 'Bahamas', nameEn: 'Bahamas', currency: 'BSD', flag: '🇧🇸' },
  { code: 'IS', name: 'Islande', nameEn: 'Iceland', currency: 'ISK', flag: '🇮🇸' },
  { code: 'MC', name: 'Monaco', nameEn: 'Monaco', currency: 'EUR', flag: '🇲🇨' },
  { code: 'LU', name: 'Luxembourg', nameEn: 'Luxembourg', currency: 'EUR', flag: '🇱🇺' },
  { code: 'LI', name: 'Liechtenstein', nameEn: 'Liechtenstein', currency: 'CHF', flag: '🇱🇮' },
  { code: 'CY', name: 'Chypre', nameEn: 'Cyprus', currency: 'EUR', flag: '🇨🇾' },
  { code: 'MT', name: 'Malte', nameEn: 'Malta', currency: 'EUR', flag: '🇲🇹' },
  { code: 'QA', name: 'Qatar', nameEn: 'Qatar', currency: 'QAR', flag: '🇶🇦' },
  { code: 'KW', name: 'Koweït', nameEn: 'Kuwait', currency: 'KWD', flag: '🇰🇼' },
  { code: 'BH', name: 'Bahreïn', nameEn: 'Bahrain', currency: 'BHD', flag: '🇧🇭' },
  { code: 'OM', name: 'Oman', nameEn: 'Oman', currency: 'OMR', flag: '🇴🇲' },
  { code: 'LB', name: 'Liban', nameEn: 'Lebanon', currency: 'LBP', flag: '🇱🇧' },
  { code: 'JO', name: 'Jordanie', nameEn: 'Jordan', currency: 'JOD', flag: '🇯🇴' },
  { code: 'IQ', name: 'Irak', nameEn: 'Iraq', currency: 'IQD', flag: '🇮🇶' },
  { code: 'IR', name: 'Iran', nameEn: 'Iran', currency: 'IRR', flag: '🇮🇷' },
  { code: 'LK', name: 'Sri Lanka', nameEn: 'Sri Lanka', currency: 'LKR', flag: '🇱🇰' },
  { code: 'NP', name: 'Népal', nameEn: 'Nepal', currency: 'NPR', flag: '🇳🇵' },
  { code: 'MV', name: 'Maldives', nameEn: 'Maldives', currency: 'MVR', flag: '🇲🇻' },
  { code: 'MN', name: 'Mongolie', nameEn: 'Mongolia', currency: 'MNT', flag: '🇲🇳' },
  { code: 'KZ', name: 'Kazakhstan', nameEn: 'Kazakhstan', currency: 'KZT', flag: '🇰🇿' },
  { code: 'UZ', name: 'Ouzbékistan', nameEn: 'Uzbekistan', currency: 'UZS', flag: '🇺🇿' },
  { code: 'GE', name: 'Géorgie', nameEn: 'Georgia', currency: 'GEL', flag: '🇬🇪' },
  { code: 'AM', name: 'Arménie', nameEn: 'Armenia', currency: 'AMD', flag: '🇦🇲' },
  { code: 'AZ', name: 'Azerbaïdjan', nameEn: 'Azerbaijan', currency: 'AZN', flag: '🇦🇿' },
  { code: 'FJ', name: 'Fidji', nameEn: 'Fiji', currency: 'FJD', flag: '🇫🇯' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', nameEn: 'Papua New Guinea', currency: 'PGK', flag: '🇵🇬' },
  // African Countries mapping inside GLOBAL_COUNTRIES for unified global experience
  { code: 'DZ', name: 'Algérie', nameEn: 'Algeria', currency: 'DZD', flag: '🇩🇿' },
  { code: 'AO', name: 'Angola', nameEn: 'Angola', currency: 'AOA', flag: '🇦🇴' },
  { code: 'BJ', name: 'Bénin', nameEn: 'Benin', currency: 'XOF', flag: '🇧🇯' },
  { code: 'BW', name: 'Botswana', nameEn: 'Botswana', currency: 'BWP', flag: '🇧🇼' },
  { code: 'BF', name: 'Burkina Faso', nameEn: 'Burkina Faso', currency: 'XOF', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', nameEn: 'Burundi', currency: 'BIF', flag: '🇧🇮' },
  { code: 'CV', name: 'Cap-Vert', nameEn: 'Cape Verde', currency: 'CVE', flag: '🇨🇻' },
  { code: 'CM', name: 'Cameroun', nameEn: 'Cameroon', currency: 'XAF', flag: '🇨🇲' },
  { code: 'CF', name: 'Centrafrique', nameEn: 'Central African Republic', currency: 'XAF', flag: '🇨🇫' },
  { code: 'TD', name: 'Tchad', nameEn: 'Chad', currency: 'XAF', flag: '🇹🇩' },
  { code: 'KM', name: 'Comores', nameEn: 'Comoros', currency: 'KMF', flag: '🇰🇲' },
  { code: 'CG', name: 'Congo', nameEn: 'Congo', currency: 'XAF', flag: '🇨🇬' },
  { code: 'CD', name: 'RD Congo', nameEn: 'DR Congo', currency: 'CDF', flag: '🇨🇩' },
  { code: 'CI', name: "Côte d'Ivoire", nameEn: "Côte d'Ivoire", currency: 'XOF', flag: '🇨🇮' },
  { code: 'DJ', name: 'Djibouti', nameEn: 'Djibouti', currency: 'DJF', flag: '🇩🇯' },
  { code: 'EG', name: 'Égypte', nameEn: 'Egypt', currency: 'EGP', flag: '🇪🇬' },
  { code: 'GQ', name: 'Guinée Équatoriale', nameEn: 'Equatorial Guinea', currency: 'XAF', flag: '🇬🇶' },
  { code: 'ER', name: 'Érythrée', nameEn: 'Eritrea', currency: 'ERN', flag: '🇪🇷' },
  { code: 'SZ', name: 'Eswatini', nameEn: 'Eswatini', currency: 'SZL', flag: '🇸🇿' },
  { code: 'ET', name: 'Éthiopie', nameEn: 'Ethiopia', currency: 'ETB', flag: '🇪🇹' },
  { code: 'GA', name: 'Gabon', nameEn: 'Gabon', currency: 'XAF', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambie', nameEn: 'Gambia', currency: 'GMD', flag: '🇬🇲' },
  { code: 'GH', name: 'Ghana', nameEn: 'Ghana', currency: 'GHS', flag: '🇬🇭' },
  { code: 'GN', name: 'Guinée', nameEn: 'Guinea', currency: 'GNF', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinée-Bissau', nameEn: 'Guinea-Bissau', currency: 'XOF', flag: '🇬🇼' },
  { code: 'KE', name: 'Kenya', nameEn: 'Kenya', currency: 'KES', flag: '🇰🇪' },
  { code: 'LS', name: 'Lesotho', nameEn: 'Lesotho', currency: 'LSL', flag: '🇱🇸' },
  { code: 'LR', name: 'Liberia', nameEn: 'Liberia', currency: 'LRD', flag: '🇱🇷' },
  { code: 'LY', name: 'Libye', nameEn: 'Libya', currency: 'LYD', flag: '🇱🇾' },
  { code: 'MG', name: 'Madagascar', nameEn: 'Madagascar', currency: 'MGA', flag: '🇲🇬' },
  { code: 'MW', name: 'Malawi', nameEn: 'Malawi', currency: 'MWK', flag: '🇲🇼' },
  { code: 'ML', name: 'Mali', nameEn: 'Mali', currency: 'XOF', flag: '🇲🇱' },
  { code: 'MR', name: 'Mauritanie', nameEn: 'Mauritania', currency: 'MRU', flag: '🇲🇷' },
  { code: 'MU', name: 'Maurice', nameEn: 'Mauritius', currency: 'MUR', flag: '🇲🇺' },
  { code: 'MA', name: 'Maroc', nameEn: 'Morocco', currency: 'MAD', flag: '🇲🇦' },
  { code: 'MZ', name: 'Mozambique', nameEn: 'Mozambique', currency: 'MZN', flag: '🇲🇿' },
  { code: 'NA', name: 'Namibie', nameEn: 'Namibia', currency: 'NAD', flag: '🇳🇦' },
  { code: 'NE', name: 'Niger', nameEn: 'Niger', currency: 'XOF', flag: '🇳🇪' },
  { code: 'NG', name: 'Nigeria', nameEn: 'Nigeria', currency: 'NGN', flag: '🇳🇬' },
  { code: 'RW', name: 'Rwanda', nameEn: 'Rwanda', currency: 'RWF', flag: '🇷🇼' },
  { code: 'ST', name: 'São Tomé-et-Príncipe', nameEn: 'São Tomé and Príncipe', currency: 'STN', flag: '🇸🇹' },
  { code: 'SN', name: 'Sénégal', nameEn: 'Senegal', currency: 'XOF', flag: '🇸🇳' },
  { code: 'SC', name: 'Seychelles', nameEn: 'Seychelles', currency: 'SCR', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', nameEn: 'Sierra Leone', currency: 'SLL', flag: '🇸🇱' },
  { code: 'SO', name: 'Somalie', nameEn: 'Somalia', currency: 'SOS', flag: '🇸🇴' },
  { code: 'ZA', name: 'Afrique du Sud', nameEn: 'South Africa', currency: 'ZAR', flag: '🇿🇦' },
  { code: 'SS', name: 'Soudan du Sud', nameEn: 'South Sudan', currency: 'SSP', flag: '🇸🇸' },
  { code: 'SD', name: 'Soudan', nameEn: 'Sudan', currency: 'SDG', flag: '🇸🇩' },
  { code: 'TZ', name: 'Tanzanie', nameEn: 'Tanzania', currency: 'TZS', flag: '🇹🇿' },
  { code: 'TG', name: 'Togo', nameEn: 'Togo', currency: 'XOF', flag: '🇹🇬' },
  { code: 'TN', name: 'Tunisie', nameEn: 'Tunisia', currency: 'TND', flag: '🇹🇳' },
  { code: 'UG', name: 'Ouganda', nameEn: 'Uganda', currency: 'UGX', flag: '🇺🇬' },
  { code: 'ZM', name: 'Zambie', nameEn: 'Zambia', currency: 'ZMW', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', nameEn: 'Zimbabwe', currency: 'ZWL', flag: '🇿🇼' },
];

// Added for genuine worldwide coverage — closed a real gap of 50 UN
// member states missing from the list above (Baltics, Balkans, Central
// Asia, Caribbean, Pacific islands, and others). North Korea and Syria
// deliberately excluded: both are under comprehensive international
// (OFAC/EU) sanctions, and most payment-processing platforms exclude
// them for the same reason — this isn't an oversight.
GLOBAL_COUNTRIES.push(
  { code: 'AD', name: 'Andorre', nameEn: 'Andorra', currency: 'EUR', flag: '🇦🇩' },
  { code: 'AF', name: 'Afghanistan', nameEn: 'Afghanistan', currency: 'AFN', flag: '🇦🇫' },
  { code: 'AG', name: 'Antigua-et-Barbuda', nameEn: 'Antigua and Barbuda', currency: 'XCD', flag: '🇦🇬' },
  { code: 'AL', name: 'Albanie', nameEn: 'Albania', currency: 'ALL', flag: '🇦🇱' },
  { code: 'BA', name: 'Bosnie-Herzégovine', nameEn: 'Bosnia and Herzegovina', currency: 'BAM', flag: '🇧🇦' },
  { code: 'BB', name: 'Barbade', nameEn: 'Barbados', currency: 'BBD', flag: '🇧🇧' },
  { code: 'BG', name: 'Bulgarie', nameEn: 'Bulgaria', currency: 'BGN', flag: '🇧🇬' },
  { code: 'BN', name: 'Brunei', nameEn: 'Brunei', currency: 'BND', flag: '🇧🇳' },
  { code: 'BT', name: 'Bhoutan', nameEn: 'Bhutan', currency: 'BTN', flag: '🇧🇹' },
  { code: 'BY', name: 'Biélorussie', nameEn: 'Belarus', currency: 'BYN', flag: '🇧🇾' },
  { code: 'BZ', name: 'Belize', nameEn: 'Belize', currency: 'BZD', flag: '🇧🇿' },
  { code: 'DM', name: 'Dominique', nameEn: 'Dominica', currency: 'XCD', flag: '🇩🇲' },
  { code: 'EE', name: 'Estonie', nameEn: 'Estonia', currency: 'EUR', flag: '🇪🇪' },
  { code: 'FM', name: 'Micronésie', nameEn: 'Micronesia', currency: 'USD', flag: '🇫🇲' },
  { code: 'GD', name: 'Grenade', nameEn: 'Grenada', currency: 'XCD', flag: '🇬🇩' },
  { code: 'GY', name: 'Guyana', nameEn: 'Guyana', currency: 'GYD', flag: '🇬🇾' },
  { code: 'HR', name: 'Croatie', nameEn: 'Croatia', currency: 'EUR', flag: '🇭🇷' },
  { code: 'KG', name: 'Kirghizistan', nameEn: 'Kyrgyzstan', currency: 'KGS', flag: '🇰🇬' },
  { code: 'KH', name: 'Cambodge', nameEn: 'Cambodia', currency: 'KHR', flag: '🇰🇭' },
  { code: 'KI', name: 'Kiribati', nameEn: 'Kiribati', currency: 'AUD', flag: '🇰🇮' },
  { code: 'KN', name: 'Saint-Christophe-et-Niévès', nameEn: 'Saint Kitts and Nevis', currency: 'XCD', flag: '🇰🇳' },
  { code: 'LA', name: 'Laos', nameEn: 'Laos', currency: 'LAK', flag: '🇱🇦' },
  { code: 'LC', name: 'Sainte-Lucie', nameEn: 'Saint Lucia', currency: 'XCD', flag: '🇱🇨' },
  { code: 'LT', name: 'Lituanie', nameEn: 'Lithuania', currency: 'EUR', flag: '🇱🇹' },
  { code: 'LV', name: 'Lettonie', nameEn: 'Latvia', currency: 'EUR', flag: '🇱🇻' },
  { code: 'MD', name: 'Moldavie', nameEn: 'Moldova', currency: 'MDL', flag: '🇲🇩' },
  { code: 'ME', name: 'Monténégro', nameEn: 'Montenegro', currency: 'EUR', flag: '🇲🇪' },
  { code: 'MH', name: 'Îles Marshall', nameEn: 'Marshall Islands', currency: 'USD', flag: '🇲🇭' },
  { code: 'MK', name: 'Macédoine du Nord', nameEn: 'North Macedonia', currency: 'MKD', flag: '🇲🇰' },
  { code: 'MM', name: 'Myanmar', nameEn: 'Myanmar', currency: 'MMK', flag: '🇲🇲' },
  { code: 'NR', name: 'Nauru', nameEn: 'Nauru', currency: 'AUD', flag: '🇳🇷' },
  { code: 'PS', name: 'Palestine', nameEn: 'Palestine', currency: 'ILS', flag: '🇵🇸' },
  { code: 'PW', name: 'Palaos', nameEn: 'Palau', currency: 'USD', flag: '🇵🇼' },
  { code: 'RS', name: 'Serbie', nameEn: 'Serbia', currency: 'RSD', flag: '🇷🇸' },
  { code: 'SB', name: 'Îles Salomon', nameEn: 'Solomon Islands', currency: 'SBD', flag: '🇸🇧' },
  { code: 'SI', name: 'Slovénie', nameEn: 'Slovenia', currency: 'EUR', flag: '🇸🇮' },
  { code: 'SK', name: 'Slovaquie', nameEn: 'Slovakia', currency: 'EUR', flag: '🇸🇰' },
  { code: 'SM', name: 'Saint-Marin', nameEn: 'San Marino', currency: 'EUR', flag: '🇸🇲' },
  { code: 'SR', name: 'Suriname', nameEn: 'Suriname', currency: 'SRD', flag: '🇸🇷' },
  { code: 'TJ', name: 'Tadjikistan', nameEn: 'Tajikistan', currency: 'TJS', flag: '🇹🇯' },
  { code: 'TL', name: 'Timor oriental', nameEn: 'Timor-Leste', currency: 'USD', flag: '🇹🇱' },
  { code: 'TM', name: 'Turkménistan', nameEn: 'Turkmenistan', currency: 'TMT', flag: '🇹🇲' },
  { code: 'TO', name: 'Tonga', nameEn: 'Tonga', currency: 'TOP', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinité-et-Tobago', nameEn: 'Trinidad and Tobago', currency: 'TTD', flag: '🇹🇹' },
  { code: 'TV', name: 'Tuvalu', nameEn: 'Tuvalu', currency: 'AUD', flag: '🇹🇻' },
  { code: 'TW', name: 'Taïwan', nameEn: 'Taiwan', currency: 'TWD', flag: '🇹🇼' },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', nameEn: 'Saint Vincent and the Grenadines', currency: 'XCD', flag: '🇻🇨' },
  { code: 'VU', name: 'Vanuatu', nameEn: 'Vanuatu', currency: 'VUV', flag: '🇻🇺' },
  { code: 'WS', name: 'Samoa', nameEn: 'Samoa', currency: 'WST', flag: '🇼🇸' },
  { code: 'YE', name: 'Yémen', nameEn: 'Yemen', currency: 'YER', flag: '🇾🇪' },
);
